server:
  port: 7788

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopme
    username: shopmeuser
    password: shopmepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect